In [1]:
import numpy as np
from IPython.display import display

# Creating a NumPy Array

In [2]:
# we can create a numpy array (matrix and vectors) using array method
x = [2, 3, 4, 5, 6]  
np_array_vect = np.array([2, 3, 4, 5, 6]) # row vector of five elements
print("vector")
print("type : {} , shape : {} ".format(type(np_array_vect),np_array_vect.shape))

vector
type : <class 'numpy.ndarray'> , shape : (5,) 


In [3]:
# creating a matrix
matrix = np.array([[2,4], [8,10], [14,16]],dtype=np.float)
print("Shape ",matrix.shape,"size ",matrix.size) # matrix shape (rows , columns)
matrix

Shape  (3, 2) size  6


array([[ 2.,  4.],
       [ 8., 10.],
       [14., 16.]])

In [4]:
# creating matrix using zeros method
zeros_vect = np.zeros(7) # vector of 7 zeros
display('zeros_vect',zeros_vect)
zeros_matrix = np.zeros((5,4)) # 5 by 4 matrix of zeros
display('zeros_matrix')
display(zeros_matrix)

'zeros_vect'

array([0., 0., 0., 0., 0., 0., 0.])

'zeros_matrix'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# creating matrix using ones method
zeros_vect = np.ones(8) # vector of 7 ones
print("ones_vect")
display(zeros_vect)
zeros_matrix = np.ones((8,8))
print("ones_matrix")
display(zeros_matrix)

ones_vect


array([1., 1., 1., 1., 1., 1., 1., 1.])

ones_matrix


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# using rand method
randomuni = np.random.rand(2, 3) # generates 2 by 3 matrix uniformly distributed 
print("random matrix uniform distributed")
display(randomuni)
# uniform ditribution : http://mathworld.wolfram.com/UniformDistribution.html
randomnorm = np.random.randn(2, 3)
# normal ditribution : http://mathworld.wolfram.com/NormalDistribution.html
print("random matrix normally distributed")
display(randomnorm)

random matrix uniform distributed


array([[0.65631346, 0.2809524 , 0.07442725],
       [0.96360347, 0.94893609, 0.13276352]])

random matrix normally distributed


array([[-0.05808127,  0.06238891,  1.72595006],
       [-0.50344779,  0.37921226, -0.5480859 ]])

In [7]:
# create matrix of random ints in specefic range 
# check : https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint
randomint = np.random.randint(low=5,high=20,size=(5,4))
#randomint = np.random.randint(low=5,high=20,size=(5,4)).astype('float')
print("random matrix of integers")
display(randomint)

random matrix of integers


array([[ 8,  6, 10,  6],
       [19, 10, 12,  6],
       [ 8,  8, 12, 16],
       [15,  6,  8, 15],
       [18, 12, 16,  9]])

# Array reshaping

In [8]:
# Reshape 1D to 2D Array
nums = np.arange(1, 17)
print('nums')
display(nums)
nums2 = nums.reshape(4, 4)
print('nums reshaped intp 4 by 4 matrix')
display(nums2)
# from 2D to 1D (flatten a matrix)
two_d = np.array([[2,3,4], [5,6,7]])
print('two_d')
display(two_d)
flat=two_d.reshape(1,-1)
print('two_d converted into flat')
display(flat)
print("two_d shape : {} flat shape : {}".format(two_d.shape,flat.shape))

# more examples : https://www.w3resource.com/numpy/manipulation/reshape.php

nums


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

nums reshaped intp 4 by 4 matrix


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

two_d


array([[2, 3, 4],
       [5, 6, 7]])

two_d converted into flat


array([[2, 3, 4, 5, 6, 7]])

two_d shape : (2, 3) flat shape : (1, 6)


# numpy array operations

In [9]:
civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
print("average : ",civilian_deaths.mean())
print("sum : ",civilian_deaths.sum())
print("min : ",civilian_deaths.min())
print("max : ",civilian_deaths.max())
print("position of min value ",civilian_deaths.argmin())
print("position of max value ",civilian_deaths.argmax())

# element wise operations
twod = np.array(([10,2,3],[40,5,6],[7,80,9]))
print("twod - 10")
display(twod-10)
print("twod * 5")
display(twod * 5)
print("log twod")
display(np.log(twod))
print("exp twod")
display(np.exp(twod))

average :  2096.0
sum :  10480
min :  233
max :  4352
position of min value  1
position of max value  0
twod - 10


array([[ 0, -8, -7],
       [30, -5, -4],
       [-3, 70, -1]])

twod * 5


array([[ 50,  10,  15],
       [200,  25,  30],
       [ 35, 400,  45]])

log twod


array([[2.30258509, 0.69314718, 1.09861229],
       [3.68887945, 1.60943791, 1.79175947],
       [1.94591015, 4.38202663, 2.19722458]])

exp twod


array([[2.20264658e+04, 7.38905610e+00, 2.00855369e+01],
       [2.35385267e+17, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 5.54062238e+34, 8.10308393e+03]])

In [10]:
# test whether none of the elements of a given array is zero
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [11]:
# test if any of the elements of a given array is non-zero
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test if any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test if any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test if any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test if any of the elements of a given array is non-zero:
False


In [12]:
# test element-wise for NaN of a given array
a = np.array([1, 0, np.nan, 5,np.nan])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))
print(np.sum(np.isnan(a))) # get how many nanas

Original array
[ 1.  0. nan  5. nan]
Test element-wise for NaN:
[False False  True False  True]
2


In [13]:
# element wise comparison
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [14]:
# np.sum ()
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [15]:
# appending new rows and columns
a = np.array([[1, 2, 3],[-1,-2,-3]])
append_rows = np.append (a, [[10, 11, 12]],axis=0)
append_cols = np.append (a, [[10], [11]],axis=1)
print("append new row")
display(append_rows)
print("append new column")
display(append_cols)

append new row


array([[ 1,  2,  3],
       [-1, -2, -3],
       [10, 11, 12]])

append new column


array([[ 1,  2,  3, 10],
       [-1, -2, -3, 11]])

In [16]:
# custom function for element wise operation
# convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# indexing and slicing

In [17]:
nums2d = np.array(([1,2,3],[4,5,6],[7,8,9]))  
nums2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# get elemetns by index
print("element at first row and first column = {}".format(nums2d[0,0]))
print("element at second row and last column = {}".format(nums2d[1,2]))
print("last column = {}".format(nums2d[:,2]))
print("upper left matrix \n {}".format(nums2d[:2,:2]))
# To get several and indepent columns
display("first and last column",nums2d[:,[0,2]])
# To get several and indepent rows
display("first and last row",nums2d[[0,2],:])

element at first row and first column = 1
element at second row and last column = 6
last column = [3 6 9]
upper left matrix 
 [[1 2]
 [4 5]]


'first and last column'

array([[1, 3],
       [4, 6],
       [7, 9]])

'first and last row'

array([[1, 2, 3],
       [7, 8, 9]])

#### quiz  : write a python function to get middle element of square array

### Flattening numpy arrays

In [19]:
array = np.array(([1,2,3],[4,5,6],[7,8,9]))
display('before flattening',array,'shape',array.shape)
vector=array.flatten()
display('after flattening',vector,'shape',vector.shape)

'before flattening'

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

'shape'

(3, 3)

'after flattening'

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

'shape'

(9,)

### np.where()
we may want to search for indexes and values that satisfy some conditions

In [62]:
array=np.random.randint(low=1,high=50,size=(5,5))
display(array)
# assume we want to threshold this array values lower than 25 will be zero and values higher than 25 will be ones
display('thresholding',np.where(array>25,1,0))
# select values based on conditions
display('values in array satisfies some conditions',array[np.where(np.logical_and(array<25,array>10))])

array([[ 1,  2, 42, 36, 31],
       [19, 26, 49, 49, 34],
       [10, 10, 36,  1, 23],
       [21, 48, 47, 11, 40],
       [17,  1, 21, 14, 21]])

'thresholding'

array([[0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0]])

'values in array satisfies some conditions'

array([19, 23, 21, 11, 17, 21, 14, 21])

### Vectorize custom functions
we can get vectorized function for our custom function to run in vectorized mode over all array elements

In [2]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

### apply function along axis

In [99]:
def minmax(axis):
    return max(axis)-min(axis)

array=np.random.randint(low=10,high=100,size=(5,5))
display(array)
display('min - max of every of row',np.apply_along_axis(func1d=minmax,axis=0,arr=array))

array([[13, 37, 86, 98, 75],
       [63, 24, 21, 75, 38],
       [89, 71, 65, 28, 94],
       [76, 18, 97, 48, 35],
       [25, 55, 84, 12, 79]])

'min - max of every of row'

array([76, 53, 76, 86, 59])