#### 1. Write a python function zer_pad(array) which accepts numpy array and add a border (filled with 0's) around the
    
####    Original array:
    
    [[ 1. 1. 1.]
    
    [ 1. 1. 1.]
    
    [ 1. 1. 1.]]
    
####    1 on the border and 0 inside in the array
    
    [[ 0. 0. 0. 0. 0.]
    
    [ 0. 1. 1. 1. 0.]
    
    [ 0. 1. 1. 1. 0.]
    
    [ 0. 1. 1. 1. 0.]
    
    [ 0. 0. 0. 0. 0.]]

In [7]:
# solution
def zero_pad(array):
    """
    function to pad/ add border of zeros around input array
    """
    # add new row at the end of the array
    array=np.append(array,np.zeros(array.shape[1]).reshape(1,-1),axis=0)
    array=np.insert(array,0,np.zeros(array.shape[1]).reshape(1,-1),axis=0)
    array=np.append(array,np.zeros(array.shape[0]).reshape(-1,1),axis=1)
    array=np.insert(array,0,np.zeros(array.shape[0]).reshape(1,-1),axis=1)
    return array

In [8]:
import numpy as np
from IPython.display import display
a=np.ones(shape=(7,7))
display('original array',a)
display('after padding ',zero_pad(a))

'original array'

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

'after padding '

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 2. write a function that accepts square numpy array with even shape and produce its center sub matrix

####    for example  
    
       [[7, 3, 7, 6, 2, 5],
       [9, 9, 9, 6, 1, 5],
       [7, 4, 4, 9, 3, 7],
       [7, 8, 1, 9, 3, 1],
       [5, 2, 8, 1, 1, 9],
       [8, 8, 5, 1, 3, 6]]
    
####    the function should return 
    
        [[4,9
          1,9]]

In [9]:
def center_matrix(array):
    """
    return square matrix center sub matrix
    """
    return array[array.shape[0]//2-1:array.shape[0]//2+1,array.shape[0]//2-1:array.shape[0]//2+1]

In [10]:
a=np.random.randint(low=1,high=10,size=(6,6))
display('original array',a)
display('center matrix',center_matrix(a))

'original array'

array([[2, 9, 5, 2, 7, 3],
       [9, 7, 7, 8, 6, 5],
       [9, 8, 7, 5, 2, 4],
       [1, 5, 9, 7, 3, 3],
       [8, 3, 9, 4, 9, 6],
       [3, 3, 6, 4, 5, 5]])

'center matrix'

array([[7, 5],
       [9, 7]])

#### 3.  Anagram arrays

    Examples :
    Input  :  arr1[] = {1, 5, 7, -1, 5}, arr2[] = {5, 5, 1, -1, 7}
              
    Output : True

    Input  :  arr2[] = {2, 5, 17, -1}, arr2[] = {2, 5, 170, -1}
    Output :  False

In [11]:
def anagram(arr1, arr2):
    return True if sum(arr1) == sum(arr2) else False

In [12]:
display(anagram([1, 5, 7, -1, 5],[5, 5, 1, -1, 7]))
display(anagram([2, 5, 17, -1],[2, 5, 170, -1]))

True

False

#### 4. equal frequencies
    
    assume we have an unsorted input array 
    
    Input : [1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]
    
    we need to make a new array where each element appears as many as max apperance in the input array
    
    example : for previous Input , the output should be
    
    Output =[1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2, 5, 5, 5, 3, 3, 4, 4 ,2]
    
    

In [13]:
# solution

def equal_freq(array):
    # make dict of apperance
    freq = {}
    for item in array:
        if item in freq:
            freq[item] += 1
        else:
            freq[item] = 1
    max_freq = max(freq.values())
    for key in freq:
        if freq[key] < max_freq:
            array.extend([key]*(max_freq - freq[key]))
    return array

In [14]:
display(equal_freq([1, 1, 1, 2]))
display(equal_freq([1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]))

[1, 1, 1, 2, 2, 2]

[1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2, 5, 5, 5, 3, 3, 4, 4, 2]

#### 5.Arrays: Left Rotation
#### problem : https://www.hackerrank.com/challenges/ctci-array-left-rotation/problem

In [15]:
# solution

def rotLeft(array, step):
    new = array[step:]
    new.extend(array[:step])
    return new

In [16]:
rotLeft([33, 47, 70, 37, 8 ,53, 13, 93, 71, 72 ,51 ,100 ,60 ,87, 97],4)

[8, 53, 13, 93, 71, 72, 51, 100, 60, 87, 97, 33, 47, 70, 37]

6 . 
problem : https://practice.geeksforgeeks.org/problems/remove-b-and-ac-from-a-given-string/0

In [26]:
# solution
s = input()
new = ''
for i in range(len(s)):
    if s[i] == 'b':
        pass
    elif s[i]=='c' and i!=0 and s[i-1]=='a':
        pass
    elif s[i] == 'a' and i!=len(s)-1 and s[i + 1] == 'c':
        pass
    else:
        new += s[i]
print(new)

bacaccazz
cazz


#### 6. String to number

In [18]:
str_num='423'
def str_to_int(str_num):
    char_num_map={'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,
                 '6':6,'7':7,'8':8,'9':9}
    num=0
    for i in range(len(str_num)):
        num+=char_num_map[str_num[i]]*10**(len(str_num)-i-1)
    return num

In [19]:
str_to_int('1230')-30

1200

#### 7. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
####    between 2000 and 3200 (both included).
####    The numbers obtained should be printed in a comma-separated sequence on a single line.

In [20]:
l=[]
for i in range(2000, 3201):
    if (i%7==0) and (i%5!=0):
        l.append(i)

print(l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


### Problem 8
With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.
Suppose the following input is supplied to the program:
8
Then, the output should be:
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [21]:
n=int(input())
d={}
for i in range(1,n+1):
    d[i]=i*i

print (d)

4
{1: 1, 2: 4, 3: 9, 4: 16}


In [22]:
d[4]

16

### problem 9 
write a python function that accepts an int as input and return its sum of digits

In [23]:
def sum_digits(number):
    sumd = 0
    while(number != 0):
        sumd += number % 10
        number //= 10
    return sumd

In [24]:
sum_digits(1230013559)

29

quiz (1) 

write a python functions that receive a list and return a dictionary whose keys are list items and values are digits sum
>
quiz (2)

Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
Suppose the following input is supplied to the program:
Hello world!
Then, the output should be:
UPPER CASE 1
LOWER CASE 9
>
quiz(3)

Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.
Suppose the following input is supplied to the program:
1,2,3,4,5,6,7,8,9
Then, the output should be:
1,3,5,7,9

>
quiz (4)

Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the company of a given email address. Both user names and company names are composed of letters only.

Example:
If the following email address is given as input to the program:

john@google.com

Then, the output of the program should be:

google