In [1]:
import numpy as np
from IPython.core.display import display

## Basic Concepts

In [43]:
row_vector=np.array(np.random.randint(low=0,high=5,size=5)).reshape(1,-1) # -1 in reshape means leave this axis as
row_vector

array([[2, 3, 4, 4, 1]])

In [47]:
col_vector=np.array(np.random.randint(low=0,high=5,size=5)).reshape(-1,1) # -1 in reshape means leave this axis as its current value
col_vector

array([[0],
       [3],
       [0],
       [4],
       [3]])

vector inner product
![img](../images/matvec2.gif)

In [45]:
# vector inner product
np.sum(np.transpose(row_vector)*col_vector)

31

In [4]:
# create 2*5 matrix
matrixA=np.array(np.random.randn(10)).reshape(2,5)
matrixA

array([[-0.5441533 , -0.51767824,  0.29087457,  0.12594721,  0.63209616],
       [-0.73189957,  0.36796398,  0.34421825,  1.37027323,  1.07260418]])

quiz : create 5 * 6 normally distributed random matrix , then reshape it into 5 * 6

In [18]:
tensorA=np.array(np.random.randn(1200)).reshape(20,20,3)
tensorA

array([[[-0.31051007,  0.07874404,  0.16169595],
        [ 0.65895726,  0.97589873,  0.63621598],
        [ 0.09070157,  1.6273107 , -0.19826193],
        ...,
        [ 0.83070327, -0.68793188,  0.05703594],
        [ 0.72275999,  0.37668045,  2.1606227 ],
        [ 0.69047708,  0.23137286, -2.59329813]],

       [[ 0.36281895,  0.01629615,  2.14433086],
        [ 1.29914074, -1.69655209, -0.06979406],
        [ 0.37514794,  2.19360911,  0.56494381],
        ...,
        [ 0.04666469, -0.04706209, -0.54682922],
        [ 0.64532158,  1.14681737, -0.22769484],
        [ 0.42321077, -0.03990572,  1.63380512]],

       [[-0.87273323,  1.96427848, -0.44452009],
        [-1.14551108,  0.87736876, -1.05904767],
        [-0.23299715,  0.01643953,  1.01537137],
        ...,
        [-1.10854495,  1.62433492,  1.26488959],
        [ 1.2915059 , -0.74062761,  0.24698424],
        [ 0.40796449, -0.70530979, -0.16829665]],

       ...,

       [[-0.03064934,  0.73277878, -0.4950499 ],
        [ 1

### Matrix Operations

In [5]:
# 1. matrix transpose
display('matrixA transpose',np.transpose(matrixA))
print('*****************************************')
# 2. add scaler to matrix element wise
display('matrixA plus 10 element wise',matrixA+10)
print('*****************************************')
# 3 add matrix to matrix element wise
X=np.array(np.random.randint(low=1,high=10,size=(4,4)))
display('X',X)
Y=np.array(np.random.randint(low=1,high=10,size=(4,4)))
display('Y',Y)
display('X+Y',X+Y)
print('*****************************************')

'matrixA transpose'

array([[-0.5441533 , -0.73189957],
       [-0.51767824,  0.36796398],
       [ 0.29087457,  0.34421825],
       [ 0.12594721,  1.37027323],
       [ 0.63209616,  1.07260418]])

*****************************************


'matrixA plus 10 element wise'

array([[ 9.4558467 ,  9.48232176, 10.29087457, 10.12594721, 10.63209616],
       [ 9.26810043, 10.36796398, 10.34421825, 11.37027323, 11.07260418]])

*****************************************


'X'

array([[4, 6, 1, 2],
       [2, 8, 1, 8],
       [8, 5, 8, 2],
       [2, 5, 2, 2]])

'Y'

array([[6, 1, 8, 7],
       [5, 1, 8, 1],
       [7, 1, 7, 1],
       [5, 2, 3, 2]])

'X+Y'

array([[10,  7,  9,  9],
       [ 7,  9,  9,  9],
       [15,  6, 15,  3],
       [ 7,  7,  5,  4]])

*****************************************


### Multiplying matrices and vectors
https://mathinsight.org/matrix_vector_multiplication

In [6]:
M1=np.array(np.random.randint(low=1,high=10,size=(2,4)))
display('M1',M1,'M1 shape',M1.shape)
V1=np.array(np.random.randint(low=1,high=10,size=(4,1)))
display('V1',V1,'V1 shape',V1.shape)
display('V1 * M1',np.matmul(M1,V1))

'M1'

array([[8, 1, 1, 1],
       [6, 2, 2, 4]])

'M1 shape'

(2, 4)

'V1'

array([[6],
       [6],
       [4],
       [6]])

'V1 shape'

(4, 1)

'V1 * M1'

array([[64],
       [80]])

## matrix by matrix

In [50]:
M2=np.array(np.random.randint(low=1,high=5,size=(2,4)))
display('M2',M2,'M2 shape',M2.shape)
M3=np.array(np.random.randint(low=1,high=5,size=(4,2)))
display('M3',M3,'M3 shape',M3.shape)
display('M2 * M3',np.matmul(M2,M3))

'M2'

array([[2, 3, 1, 4],
       [4, 4, 3, 2]])

'M2 shape'

(2, 4)

'M3'

array([[3, 3],
       [1, 1],
       [3, 1],
       [2, 3]])

'M3 shape'

(4, 2)

'M2 * M3'

array([[20, 22],
       [29, 25]])

## Matrix inverse

![img](../images/inverse-matrix.png)

In [53]:
x = np.array([[1,2],[3,4]],dtype=np.int) 
y = np.linalg.inv(x) 
display('x',x) 
display('x inverse',y) 
display('x * x inverse',np.matmul(x,y))

'x'

array([[1, 2],
       [3, 4]])

'x inverse'

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

'x * x inverse'

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

## Vector norm

Sometimes we need to measure the size (magnitude) of a vector. 

In machine learning, we usually measure the size of vectors using a function called anorm

In [54]:
v=np.array(np.random.randint(low=0,high=50,size=(2,1))) # Euclidean norm
display('vector',v,'norm',np.linalg.norm(v))
print('*****************************************')
v2=np.array(np.random.randint(low=0,high=50,size=(3,1)))
display('vector',v2,'norm',np.linalg.norm(v2))

'vector'

array([[24],
       [41]])

'norm'

47.50789408087881

*****************************************


'vector'

array([[48],
       [24],
       [46]])

'norm'

70.68238818828917

## Notes

#### A symmetric matrix is any matrix that is equal to its own transpose:

#### $ A = A^T $

#### A unit vector is a vector with unit norm :

$||x||_2=1$ 

#### A vector $x$ and a vector $y$ are orthogonal to each other if $x^Ty=0$ 

### Eigen decomposition

Many mathematical objects can be understood better by breaking them int oconstituent parts, or finding some properties of them that are universal, not caused by the way we choose to represent them.For example, integers can be decomposed into prime factors. The way we represent the number 12 will change depending on whether we write it in base ten or in binary, but it will always be true that 12 = 2×2×3. From this representation we can conclude useful properties, for example, that 12 is not divisible by 5, and that any integer multiple of 12 will be divisible by 3.Much as we can discover something about the true nature of an integer bydecomposing it into prime factors, we can also decompose matrices in ways that show us information about their functional properties that is not obvious from the representation of the matrix as an array of elements.One of the most widely used kinds of matrix decomposition is called eigen-decomposition, in which we decompose a matrix into a set of eigenvectors and eigenvalues.

an eigenvector of a square matrix $A$ is a nonzero vector $v$ such that multi-plication by $A$ alters only the scale of $v$
### $ A v=\lambda v $


In [3]:
from numpy import linalg as LA
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
display(A)
eigvalues, eigvectors = LA.eig(A)
display('eign values',eigvalues,'eign vectors',eigvectors)

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 1,  0, -1]])

'eign values'

array([ 4.31662479e+00, -2.31662479e+00,  1.93041509e-17])

'eign vectors'

array([[ 0.58428153,  0.73595785,  0.40824829],
       [ 0.80407569, -0.38198836, -0.81649658],
       [ 0.10989708, -0.55897311,  0.40824829]])