In [1]:
import numpy as np
from IPython.core.display import display

In [2]:
col_vector=np.array(np.random.randn(5)).reshape(-1,1)
col_vector

array([[-0.15419724],
       [-0.12374509],
       [ 0.44485891],
       [ 0.58407357],
       [-0.78578741]])

In [3]:
matrixA=np.array(np.random.randn(10)).reshape(2,5)
matrixA

array([[-1.07546657, -1.76510942,  0.54251026, -1.61181762, -0.66600756],
       [-0.85674908,  1.74351943,  2.08690698, -0.97040685,  0.10933447]])

quiz : create 5*6 normally distributed random matrix

In [4]:
tensorA=np.array(np.random.randn(1200)).reshape(20,20,3)
tensorA

array([[[ 0.43426807,  1.44830168, -1.64554765],
        [ 0.16460869,  0.72056185, -0.55033517],
        [ 0.58720926,  1.236567  ,  1.01639729],
        ...,
        [-1.55858799,  0.3576021 ,  1.03296574],
        [-1.57451514, -1.1785179 ,  0.71262467],
        [ 0.8974751 , -0.01787138, -2.21053222]],

       [[ 1.62500086,  1.35918897, -0.73511914],
        [-0.05655172, -0.48086408,  0.72719168],
        [-1.33833654,  0.19078875, -0.15494283],
        ...,
        [-0.12861112,  0.60882558,  0.85754825],
        [-2.12987202,  0.77183696,  0.26675549],
        [-2.0972399 , -1.08813405,  0.37825299]],

       [[-0.60192483,  0.27502373, -0.33251479],
        [ 0.0414718 ,  1.31769981, -1.68442788],
        [-0.50740596,  1.26901824, -0.29629078],
        ...,
        [-0.38299458, -0.40498631,  0.43344005],
        [ 0.09832888,  0.9113714 ,  0.14219581],
        [ 0.16187851, -0.58629811,  0.66927112]],

       ...,

       [[ 2.05039958,  1.31914518,  1.18258582],
        [ 0

### Matrix Operations

In [5]:
# 1. matrix transpose
display('matrixA transpose',np.transpose(matrixA))
print('*****************************************')
# 2. add scaler to matrix element wise
display('matrixA plus 10 element wise',matrixA+10)
print('*****************************************')
# 3 add matrix to matrix element wise
X=np.array(np.random.randint(low=1,high=10,size=(4,4)))
display('X',X)
Y=np.array(np.random.randint(low=1,high=10,size=(4,4)))
display('Y',Y)
display('X+Y',X+Y)
print('*****************************************')

'matrixA transpose'

array([[-1.07546657, -0.85674908],
       [-1.76510942,  1.74351943],
       [ 0.54251026,  2.08690698],
       [-1.61181762, -0.97040685],
       [-0.66600756,  0.10933447]])

*****************************************


'matrixA plus 10 element wise'

array([[ 8.92453343,  8.23489058, 10.54251026,  8.38818238,  9.33399244],
       [ 9.14325092, 11.74351943, 12.08690698,  9.02959315, 10.10933447]])

*****************************************


'X'

array([[7, 8, 5, 8],
       [6, 9, 9, 2],
       [3, 6, 7, 9],
       [6, 2, 4, 7]])

'Y'

array([[9, 5, 1, 6],
       [9, 4, 4, 1],
       [9, 4, 4, 8],
       [6, 4, 5, 6]])

'X+Y'

array([[16, 13,  6, 14],
       [15, 13, 13,  3],
       [12, 10, 11, 17],
       [12,  6,  9, 13]])

*****************************************


### Multiplying matrices and vectors
https://mathinsight.org/matrix_vector_multiplication

In [6]:
M1=np.array(np.random.randint(low=1,high=10,size=(2,4)))
display('M1',M1,'M1 shape',M1.shape)
V1=np.array(np.random.randint(low=1,high=10,size=(4,1)))
display('V1',V1,'V1 shape',V1.shape)
display('V1 * M1',np.matmul(M1,V1))

'M1'

array([[8, 1, 1, 1],
       [6, 2, 2, 4]])

'M1 shape'

(2, 4)

'V1'

array([[6],
       [6],
       [4],
       [6]])

'V1 shape'

(4, 1)

'V1 * M1'

array([[64],
       [80]])

## matrix by matrix

In [7]:
M2=np.array(np.random.randint(low=1,high=10,size=(2,4)))
display('M2',M2,'M2 shape',M2.shape)
M3=np.array(np.random.randint(low=1,high=10,size=(4,2)))
display('M2',M2,'M2 shape',M2.shape)
display('V1 * M1',np.matmul(M2,M3))

'M2'

array([[4, 8, 6, 5],
       [5, 5, 3, 6]])

'M2 shape'

(2, 4)

'M2'

array([[4, 8, 6, 5],
       [5, 5, 3, 6]])

'M2 shape'

(2, 4)

'V1 * M1'

array([[ 97, 187],
       [ 77, 160]])

## Matrix inverse

In [8]:
x = np.array([[1,2],[3,4]],dtype=np.int) 
y = np.linalg.inv(x) 
display('x',x) 
display('x inverse',y) 
display('x * x inverse',np.matmul(x,y))

'x'

array([[1, 2],
       [3, 4]])

'x inverse'

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

'x * x inverse'

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

## Vector norm

Sometimes we need to measure the size (magnitude) of a vector. In machine learning, we usuallymeasure the size of vectors using a function called anorm

In [9]:
v=np.array(np.random.randint(low=0,high=50,size=(2,1))) # Euclidean norm
display('vector',v,'norm',np.linalg.norm(v))
print('*****************************************')
v2=np.array(np.random.randint(low=0,high=50,size=(3,1)))
display('vector',v2,'norm',np.linalg.norm(v2))

'vector'

array([[25],
       [20]])

'norm'

32.01562118716424

*****************************************


'vector'

array([[15],
       [32],
       [12]])

'norm'

37.322915213043046

## Notes

#### A symmetric matrix is any matrix that is equal to its own transpose:

#### $ A = A^T $

#### A unit vector is a vector with unit norm :

$||x||_2=1$ 

#### A vector $x$ and a vector $y$ are orthogonal to each other if $x^Ty=0$ 

### Eigendecomposition

Many mathematical objects can be understood better by breaking them int oconstituent parts, or finding some properties of them that are universal, not causedby the way we choose to represent them.For example, integers can be decomposed into prime factors. The way werepresent the number 12 will change depending on whether we write it in base ten or in binary, but it will always be true that 12 = 2×2×3. From this representation we can conclude useful properties, for example, that 12 is not divisible by 5, and that any integer multiple of 12 will be divisible by 3.Much as we can discover something about the true nature of an integer bydecomposing it into prime factors, we can also decompose matrices in ways that show us information about their functional properties that is not obvious from the representation of the matrix as an array of elements.One of the most widely used kinds of matrix decomposition is called eigen-decomposition, in which we decompose a matrix into a set of eigenvectors andeigenvalues.

an eigenvector of a square matrix $A$ is a nonzero vector $v$ such that multi-plication by $A$ alters only the scale of $v$
### $ A v=\lambda v $


In [11]:
from numpy import linalg as LA
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
eigvalues, eigvectors = LA.eig(A)
display('eign values',eigvalues,'eign vectors',eigvectors)

'eign values'

array([ 4.31662479e+00, -2.31662479e+00,  1.93041509e-17])

'eign vectors'

array([[ 0.58428153,  0.73595785,  0.40824829],
       [ 0.80407569, -0.38198836, -0.81649658],
       [ 0.10989708, -0.55897311,  0.40824829]])